import { Open_Sans, Geist_Mono, Frank_Ruhl_Libre, Varela_Round, Geist, Cinzel_Decorative } from "next/font/google";
import "./globals.css";

const open_sans = Open_Sans({
  variable: "--font-o",
  subsets: ["latin"],
  weight: ['300', '400', '500', '800', '700', '800'],
});

const frank = Frank_Ruhl_Libre({
  variable: "--font-f",
  subsets: ["latin"],
  weight: ['300', '400', '500', '800', '700', '800'],
});

const cinzel = Cinzel_Decorative({
  variable: "--font-c",
  subsets: ["latin"],
  weight: ['400', '700', '900'],
});

const varela = Varela_Round({ subsets: ["latin"], weight: ['400'], variable: "--font-a" })


export const metadata = {
  title: "My App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${open_sans.variable} ${cinzel.variable} ${varela.variable} ${frank.variable}`}>
        {children}
      </body>
    </html>
  );
}
